### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by Rokt33r** [Rokt33r/oh-my-cdn#1]
- [ ] Add test
- [ ] Colored log
- [ ] `targets` key also accept Array
- [ ] more options for CLI
  - [ ] add command `oh-my-cdn add $NAME $URL --filename=$FILENAME`
  - [ ] remove command `oh-my-cdn rm $NAME`
  - [ ] `--version`, `-v`
  - [ ] `--quiet`
  - [ ] `--prune`
  - [ ] `--help`, `-h`
